version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      npm:
        patterns:
          - "*"
    labels:
      - dependencies
      - npm
